Add Eth-wallets support
near-examples/hello-near-examples pull request #21
Opened 2024-09-23 13:40 UTC by Karkunow

This PR adds an example of the Eth-wallets integration from the Near Wallet Selector and [NEP-518](https://github.com/near/NEPs/issues/518) support.
See the additional docs here:
https://github.com/near/wallet-selector/blob/9a9f9535ec57633b949872bb51903e7802beb3e8/packages/ethereum-wallets/README.md

2024-09-23 13:46 UTC, frol reviewed
This looks good to me overall. Sorry for bothering you with the formatting nits.

@gagdiez Please, review as well

2024-09-23 13:46 UTC, frol commented on frontend/src/wallets/web3modal.js
> +};
Please, fix the formatting here

2024-09-23 13:46 UTC, frol commented on frontend/src/wallets/web3modal.js
Please, format this file with 2-spaces indentation

2024-09-23 14:02 UTC, Karkunow commented
@frol done with the formatting fixes

2024-09-24 16:31 UTC, gagdiez requested changes

2024-09-24 16:31 UTC, gagdiez commented on frontend/src/wallets/near.js
> +   * const wallet = new Wallet({ networkId: 'testnet' });
```suggestion
   * const wallet = new Wallet({ networkId: 'testnet', createAccessKeyFor: 'contractId' });
```

lets bring `createAccessKeyFor` back here, as it is a valid case (people might want to add a key for their specific project

2024-09-24 16:31 UTC, gagdiez commented on frontend/src/wallets/near.js
> +    const modal = setupModal(await this.selector, { contractId: "" });
```suggestion
    const modal = setupModal(await this.selector, { contractId: this.createAccessKeyFor });
```

same here

2024-09-24 16:31 UTC, gagdiez commented on frontend/src/wallets/near.js
> +  constructor({ networkId = 'testnet'}) {
```suggestion
  constructor({ networkId = 'testnet'}, createAccessKeyFor = undefined }) {
    this.createAccessKeyFor = createAccessKeyFor;
```

2024-09-24 16:31 UTC, gagdiez commented on frontend/src/wallets/near.js
> +        setupEthereumWallets({ wagmiConfig, web3Modal, alwaysOnboardDuringSignIn }),
```suggestion
        setupEthereumWallets({ wagmiConfig, web3Modal, alwaysOnboardDuringSignIn: true }),
```

maybe we just add the `true` inside of the object

2024-09-24 16:32 UTC, gagdiez commented
almost there! small changes request and we can merge this @Karkunow

2024-09-25 10:10 UTC, gagdiez approved these changes

2024-09-25 10:10 UTC, merged